- helpers/04-events/event-router.js
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings
> BE- Routes

- helpers/03-templates/template-model.js
> Terrell tullis

- helpers/01-users/user-router.js
- helpers/02-groups/group-model.js
- helpers/02-groups/group-router.js
> Jacob mcfaul

- helpers/04-events/event-model.js
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Complete, tested, ready to review and merge
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My code has been reviewed by at least one peer
- [ x ] I have commented my code, particularly in hard-to-understand areas
> Update and delete in Events

- helpers/02-groups/group-model.js
> added find function to group model

- helpers/03-templates/template-router.js
> Removed duplicate delete endpoint, and added Edit/Update, and get template events by ID

- auth-routes/auth-router.js
- package.json
- yarn.lock
> added pg to package.json

- migrations/tables.js
- seeds/04-events.js
> changed the migrations db

- auth-routes/auth-router.js
> a very meaningful commit

- helpers/04-events/event-model.js
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Complete, but not tested (may need new tests)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [ x] My changes generate no new warnings
- [x ] There are no merge conflicts
> makes changes to update and add helpers in event-model

- auth-routes/auth-router.js
- config/passport-setup.js
> Zechariah drinkhall

- helpers/01-users/user-model.js
- helpers/01-users/user-router.js
- helpers/02-groups/group-model.js
- helpers/02-groups/group-router.js
- helpers/03-templates/template-model.js
- helpers/03-templates/template-router.js
- helpers/04-events/event-model.js
- migrations/tables.js
- seeds/04-events.js
> added dynamic post endpoints for groups, templates and events

- auth-routes/auth-router.js
- helpers/02-groups/group-router.js
- migrations/tables.js
- seeds/04-events.js
> created logout redirect route and updated events table with more inputs

- api/server.js
- helpers/04-templates/template-model.js
- helpers/04-templates/template-router.js
> fixed post in template/event to add title and description

- auth-routes/auth-router.js
> changed backend routes

- api/server.js
> cors options

- migrations/tables.js
> fixed template table issue

- helpers/02-groups/group-router.js
> error testing

- helpers/02-groups/group-model.js
> fixed function

- helpers/02-groups/group-router.js
> fixed bug that i lied about fixing 5 seconds ago

- api/server.js
- auth-routes/auth-router.js
> refactired links to dotenv

- helpers/01-users/user-router.js
- helpers/02-groups/group-model.js
- helpers/02-groups/group-router.js
- migrations/tables.js
- seeds/02-groups.js
- seeds/03-templates.js
> edited some of the migrations and functions for them

- helpers/04-templates/template-model.js
- helpers/04-templates/template-router.js
- migrations/tables.js
> updating table

- auth-routes/auth-router.js
- helpers/02-groups/group-model.js
- helpers/02-groups/group-router.js
- migrations/tables.js
> fixed everything so color is out and routes

- api/server.js
- helpers/01-users/user-model.js
- helpers/01-users/user-router.js
- migrations/tables.js
> added premium status functionality for users and group posting

- api/server.js
- helpers/01-users/user-router.js
> minor update to updating users

- helpers/02-groups/group-model.js
- helpers/02-groups/group-router.js
> updated group join function

- api/server.js
> Max trestman

- helpers/02-groups/group-router.js
> updated the object return from the group join

- api/server.js
- helpers/01-users/user-router.js
- helpers/02-groups/group-router.js
> fixed number

- knexfile.js
> minor updates
